on: [push, pull_request]

name: rust

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: install cargo-tarpaulin
      run: cargo install cargo-tarpaulin
    - name: install clippy
      run: rustup component add clippy
    - name: install rustfmt
      run: rustup component add rustfmt
    - name: install cargo-audit
      run: cargo install cargo-audit

    - name: test
      run: cargo test
    - name: tarpauline
      run: cargo tarpaulin --ignore-tests
    - name: clippy
      run: cargo clippy -D warnings
    - name: fmt
      run: cargo fmt --check
    - name: audit
      run: cargo audit
